# Generated by Django 4.1 on 2024-09-04 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_pic_url", models.URLField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gender", models.CharField(max_length=10)),
                ("accept_terms", models.BooleanField(default=False)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Merchant", "Merchant"),
                            ("Admin", "ShopOkoa Admin"),
                            ("Buyer", "Buyer"),
                        ],
                        default="Buyer",
                        max_length=255,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("business_permit_url", models.URLField(blank=True, null=True)),
                (
                    "license_no",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "kra_pin",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "national_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("location", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
